export PATH="/opt/opencode/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:$PATH"
export STARSHIP_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/sandbox/starship.toml"

alias v='nvim'

eval "$(starship init bash)"
